<a href="https://colab.research.google.com/github/purna-2007/numpy_pythonlibrary_code-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy
print(numpy.__version__)
import numpy as np


2.0.2


In [47]:
a=np.array([10])
print(a)    #zero dimension

[10]


In [48]:
a=np.array([10,20])
print(a)  #one dimensional array

[10 20]


In [49]:
a=np.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [50]:
print(a[1][0])
print(a[1][1])


30
40


In [51]:
a=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(a)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [52]:
print(a[1][1][1])
print(a[0][1][0])

80
30


In [53]:
arr=np.array([10,20,30,40])
print(arr.ndim)

1


In [54]:
arr=np.array([[10,20],[35,30],[50,60]])
print(arr.ndim)

2


In [55]:
arr=np.zeros([3,3])# 3X3 matrix
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [56]:
arr=np.ones(2)
print(arr)

[1. 1.]


In [57]:
arr=np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [58]:
arr=np.ones([10,10])
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [59]:
arr=np.full([2,2],6)
print(arr)

[[6 6]
 [6 6]]


In [60]:
arr=np.full([3,3],6)
print(arr.dtype)

int64


In [61]:
arr=np.random.rand(2,3)
print(arr)

[[0.88286593 0.06017887 0.20445839]
 [0.62552269 0.49641973 0.36260707]]


In [62]:
arr=np.random.randint(4,5 , [3,6])
print(arr)

[[4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]]


In [63]:
arr=np.random.rand(2,3)
print(arr)

[[0.97203536 0.94031555 0.07270523]
 [0.76389353 0.18268455 0.47265867]]


In [64]:
print(np.eye(4))#identity matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [65]:
#random.randint(low,high,size=name,dtype=|n|)
arr=np.random.randint(2,size=5)
print(arr)

[1 1 1 1 0]


In [66]:
arr=np.random.randint(2,size=(3,4))
print(arr)

[[0 1 0 0]
 [1 0 0 0]
 [0 1 1 0]]


In [67]:
import numpy as np

arr = np.array([[5, 10, 15], [20, 25, 30]])
print(arr)
print("Dimensions:\n", arr.ndim)

print("The array has", arr.ndim, "dimensions:", arr.shape[0], "rows &", arr.shape[1], "columns")

[[ 5 10 15]
 [20 25 30]]
Dimensions:
 2
The array has 2 dimensions: 2 rows & 3 columns


In [68]:
import numpy as np

arr = np.array([[10, 20, 30, 50],
                [40, 50, 60, 39],
                [70, 80, 90, 38],
                [25, 35, 26, 36]])

print(arr.size)
print(arr.shape[0] * arr.shape[1])

16
16


In [69]:
arr=np.random.randint(5,size = (3,4))
print(arr)

[[3 0 4 4]
 [3 4 0 4]
 [1 0 4 0]]


In [70]:
np.random.randint(low=0, high=10, size=12, dtype=int)
arr=np.random.randint(2,size=5)
print(arr)

[1 0 1 1 1]


In [71]:
arr=np.array([[4,5,6],[7,8,9]])
print(arr.ndim)

2


In [72]:
arr=np.array([[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)

(2, 3)
6


**flatten**

In [73]:
import numpy as np
arr=np.array([[6,9,3],[8,7,1]])
print(arr.flatten())

[6 9 3 8 7 1]


In [74]:
import numpy as np
arr=np.array([[6,9,3],[8,7,1]])
print(arr.flatten().max())

9


In [75]:
import numpy as np
a=np.array([[9,0,2],[6,3,4]])
b=np.array([[4,5,3],[8,6,9]])
result=np.concatenate((a,b))
print(result)

[[9 0 2]
 [6 3 4]
 [4 5 3]
 [8 6 9]]


In [76]:
import numpy as np
a=np.array([[9,0,2],[6,3,4]])
b=np.array([[4,5,3],[8,6,9]])
c=np.array([[8,4,6],[9,6,7]])
result=np.concatenate(((a.flatten(),b.flatten(),c.flatten())))
print(result)

[9 0 2 6 3 4 4 5 3 8 6 9 8 4 6 9 6 7]


ravel is a change an entire array also and flatten has only can change in change that only array

In [77]:
import numpy as np
arr=np.array([[9,0,2],[6,3,4]])
res=arr.flatten()
res[2]=31
print(res)
print(arr)


[ 9  0 31  6  3  4]
[[9 0 2]
 [6 3 4]]


In [78]:
import numpy as np
arr=np.array([[9,0,2],[6,3,4]])
res=arr.ravel()
res[2]=31
print(res,'\n')
print(arr)


[ 9  0 31  6  3  4] 

[[ 9  0 31]
 [ 6  3  4]]


TRANSPOSE

In [79]:
arr=np.array([[9,0,2],[6,3,4]])
print(arr.transpose())

[[9 6]
 [0 3]
 [2 4]]


reshape

In [80]:
arr=np.array([[9,0,2],[6,3,4]])
print(arr.reshape(3,2))

[[9 0]
 [2 6]
 [3 4]]


arange & linespace

In [81]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [83]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [84]:
arr=np.array([3,4,8,2,6])
print(sorted(arr))

[np.int64(2), np.int64(3), np.int64(4), np.int64(6), np.int64(8)]


In [85]:
arr=np.array([3,4,8,2,6])
print(np.sort(arr))

[2 3 4 6 8]


In [86]:
a=np.array([[4,8,3,7,5,8,2,6],[5,6,8,3,6,2,5,9]])
print(np.sort(a))

[[2 3 4 5 6 7 8 8]
 [2 3 5 5 6 6 8 9]]


In [87]:
a=np.array([[4,8,3,7,5,8,2,6],[5,6,8,3,6,2,5,9],[6,8,3,5,9,3,7,2]])
print(np.sort(a))

[[2 3 4 5 6 7 8 8]
 [2 3 5 5 6 6 8 9]
 [2 3 3 5 6 7 8 9]]


In [88]:
import numpy as np
arr = np.array([3, 4, 8, 2, 6])
print(np.sort(arr))

[2 3 4 6 8]


In [89]:
arr=np.array([10,20,30,40,50,60,70])
print(arr[1:5])

[20 30 40 50]


In [90]:
arr=np.array([10,20,30,40,50,60,70])
print(arr[1:])

[20 30 40 50 60 70]


In [91]:
arr=np.array([10,20,30,40,50,60,70])
print(arr[:5])

[10 20 30 40 50]


In [92]:
arr=np.array([10,20,30,40,50,60,70])
print(arr[::2])

[10 30 50 70]


In [93]:
arr=np.array([10,20,30,40,50,60,70])
print(arr[-3:])

[50 60 70]


In [94]:
arr=np.array([10,20,30,40,50,60,70])
print(arr[:-2])

[10 20 30 40 50]


In [95]:
arr=np.array([10,20,30,40,50,60,70])
print(arr[::-2])# count the step size in double slicing

[70 50 30 10]


In [96]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d[0:2,1:3])#(rows,columns)

[[2 3]
 [6 7]]


In [97]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d[:2,:])#(rows,columns)

[[1 2 3 4]
 [5 6 7 8]]


In [98]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d[:,1:])#(rows,columns)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [99]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d[::-1 ,:])#(rows,columns

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [100]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d[::-2 ,:])#(rows,columns

[[ 9 10 11 12]
 [ 1  2  3  4]]


In [101]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d[1: ,2:])#(rows,columns

[[ 7  8]
 [11 12]]


In [102]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d[:,:-1 ])#(rows,columns

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
